# Generated by Django 2.2.4 on 2019-08-20 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='passenger',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='flights.Passenger'),
        ),
    ]
